export { default as WelcomeStep } from './WelcomeStep';
export { default as UserTypeStep } from './UserTypeStep';
export { default as StudentBasicInfoStep } from './StudentBasicInfoStep';
export { default as ProfessionalBasicInfoStep } from './ProfessionalBasicInfoStep';
export { default as TeacherBasicInfoStep } from './TeacherBasicInfoStep';
export { default as InterestsStep } from './InterestsStep';
export { default as GoalsStep } from './GoalsStep';
export { default as DemographicsStep } from './DemographicsStep';
export { default as ThankYouStep } from './ThankYouStep';